### ISSUE TITLE
Does not have .debug_info section error

### ISSUE THREAD

**Issue by petems** [jvns/ruby-stacktrace#16]
I'm trying to test some Ruby code that hangs in Ruby 2.3.1 (see https://bugs.ruby-lang.org/issues/12832)

``` ruby
module Foo
  private

  def foo
    "foo"
  end
end

class Bar
  extend Foo

  class << self
    public :foo
  end
end

module Baz
end

class Bar
  class << self
    prepend Baz
  end
end
Bar.method(:foo) # will hang here
```

When I run it and try to stacktrace it I get an error...

```
[root@localhost ruby-stacktrace]# ruby hang_ruby.rb &
[1] 19975
[root@localhost ruby-stacktrace]# RUST_BACKTRACE=1 ruby-stacktrace top 19975
thread 'main' panicked at 'Does not have .debug_info section', ../src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Does not have .debug_info section', ../src/libcore/option.rs:700
stack backtrace:
   1:     0x7f5a4e126ac9 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x7f5a4e12bcac - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x7f5a4e12af59 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x7f5a4e12b5e8 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x7f5a4e12b442 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x7f5a4e12b3b0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x7f5a4e12b331 - rust_begin_unwind
   8:     0x7f5a4e165e7f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x7f5a4e165ef5 - core::option::expect_failed::h1d846c7a667396f7
  10:     0x7f5a4e06a722 - ruby_stacktrace::dwarf::obj::get_dwarf_entries::he47de19de2e538d4
  11:     0x7f5a4e0594f4 - ruby_stacktrace::main::h33adc6edaef38f5f
  12:     0x7f5a4e133796 - __rust_maybe_catch_panic
  13:     0x7f5a4e12a6d2 - std::rt::lang_start::h53bf99b0829cc03c
  14:     0x7f5a4d44caf4 - __libc_start_main
  15:     0x7f5a4e053d28 - <unknown>
  16:                0x0 - <unknown>
[root@localhost ruby-stacktrace]#
```

At first I thought it was an error because it was hanging code, but it happens with any code:

```
 [root@localhost ~]# cat say_hello.rb
foo = 0

while true
  foo = foo + 1
end
[root@localhost ~]# ruby say_hello.rb &
[1] 20271
[root@localhost ~]# RUST_BACKTRACE=1 ruby-stacktrace top 20271
thread 'main' panicked at 'Does not have .debug_info section', ../src/libcore/option.rs:700
stack backtrace:
   1:     0x7ff245e66ac9 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x7ff245e6bcac - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x7ff245e6af59 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x7ff245e6b5e8 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x7ff245e6b442 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x7ff245e6b3b0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x7ff245e6b331 - rust_begin_unwind
   8:     0x7ff245ea5e7f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x7ff245ea5ef5 - core::option::expect_failed::h1d846c7a667396f7
  10:     0x7ff245daa722 - ruby_stacktrace::dwarf::obj::get_dwarf_entries::he47de19de2e538d4
  11:     0x7ff245d994f4 - ruby_stacktrace::main::h33adc6edaef38f5f
  12:     0x7ff245e73796 - __rust_maybe_catch_panic
  13:     0x7ff245e6a6d2 - std::rt::lang_start::h53bf99b0829cc03c
  14:     0x7ff24518caf4 - __libc_start_main
  15:     0x7ff245d93d28 - <unknown>
  16:                0x0 - <unknown>
```

Any ideas? Sorry I'm a rust noob, more of a Ruby person so not sure where to look! 😄

**Comment by jvns** [comment]
can you post a copy of the Ruby binary that you're using?

**Comment by jvns** [comment]
also if you just want to fix your problem, you could try https://github.com/tmm1/stackprof -- it should help you track down what's going on

**Comment by petems** [comment]
The Ruby binary was the one from this RPM: https://github.com/feedforce/ruby-rpm/releases/download/2.3.1/ruby-2.3.1-1.el7.centos.x86_64.rpm

**Comment by petems** [comment]
Ok, using rbenv installed 2.3.1 it worked fine, so it looks like it's caused by the binary from the RPM.

Should I upload a copy of the RPM Ruby binary to this ticket?

Also, I'll checkout stackprof also, looks neat 👍

**Comment by jvns** [comment]
yep sure! the real issue is likely that that binary doesn't have debug symbols or something, and we just need to have better error messages and an explanation of what to do ("install ruby with rbenv" is the right answer)

**Comment by kamalmarhubi** [comment]
I downloaded the RPM and pulled the ruby binary out. @jvns was right: there is no debug info included. I'm going to close this, but you might want to track #19. I'm hoping to figure out how to load debug symbols from the debuginfo package.
